std_msgs/Header header

# ESR Status6
string      canmsg

uint8       supply_1p8v_a2d
uint8       supply_n5v_a2d
uint8       wave_diff_a2d
uint8       sw_version_dsp_3rd_byte
bool        vertical_align_updated
uint8       system_power_mode
bool        found_target
bool        recommend_unconverge
uint8       factory_align_status_1
uint8       factory_align_status_2
float32     factory_misalignment
uint8       serv_align_updates_done
float32     vertical_misalignment
