std_msgs/Header header

# ESR Status2
string      canmsg

uint8       maximum_tracks_ack
uint8       rolling_count_2
bool        overheat_error
bool        range_perf_error
bool        internal_error
bool        xcvr_operational
bool        raw_data_mode
uint16      steering_angle_ack
int8        temperature
float32     veh_spd_comp_factor
uint8       grouping_mode
float32     yaw_rate_bias
string      sw_version_dsp
