std_msgs/Header header

# ESR Status4
string      canmsg

bool        truck_target_det
bool        lr_only_grating_lobe_det
bool        sidelobe_blockage
bool        partial_blockage
uint8       mr_lr_mode
uint8       rolling_count_3
uint8       path_id_acc
uint8       path_id_cmbb_move
uint8       path_id_cmbb_stat
uint8       path_id_fcw_move
uint8       path_id_fcw_stat
float32     auto_align_angle
uint8       path_id_acc_stat
