before_script:
  - apt-get update && apt-get install -y openssh-client python-catkin-tools build-essential
  - source `find /opt/ros -name setup.bash | sort | head -1` && echo $ROS_DISTRO
  - mkdir src && mv `find -maxdepth 1 -not -name . -not -name src` src/
  - rosdep update

indigo:
  image: "ros:indigo-ros-core"
  script:
    - rosdep install --from-paths src --ignore-src -y
    - catkin init
    - catkin build
