std_msgs/Header header

uint8  can_fcw_sensitivity_level
bool   can_vehicle_stationary
uint8  can_intf_minor_version
uint8  can_intf_major_version
uint8  can_brake_pedal
bool   can_high_wheel_slip
bool   can_washer_front_cmd
bool   can_wiper_front_cmd
uint8  can_wiper_speed_info
bool   can_reverse_gear
uint8  can_beam_shape_actual_right
uint8  can_beam_shape_actual_left
bool   can_main_beam_indication
uint16 can_vehicle_index
