std_msgs/Header header

bool front_dome_lights_on
bool front_dome_lights_on_is_valid
bool rear_dome_lights_on
bool rear_dome_lights_on_is_valid
bool mood_lights_on
bool mood_lights_on_is_valid
uint8 dim_level
bool dim_level_is_valid

uint8 DIM_LEVEL_MIN = 0
uint8 DIM_LEVEL_1 = 1
uint8 DIM_LEVEL_2 = 2
uint8 DIM_LEVEL_3 = 3
uint8 DIM_LEVEL_4 = 4
uint8 DIM_LEVEL_5 = 5
uint8 DIM_LEVEL_6 = 6
uint8 DIM_LEVEL_7 = 7
uint8 DIM_LEVEL_8 = 8
uint8 DIM_LEVEL_9 = 9
uint8 DIM_LEVEL_10 = 10
uint8 DIM_LEVEL_11 = 11
uint8 DIM_LEVEL_MAX = 12
