# System feedback

std_msgs/Header header

bool mfa_sys_joystick_enabled       
bool mfa_sys_steer_enabled          
bool mfa_sys_auto_steer_enabled     
bool mfa_sys_hydraulics_enabled     
bool commman_output_fault           
bool input_output_fault             
bool mfa_joystick_enable_in         
bool mfa_steer_can_in               
bool mfa_steer_auto_in              
bool mfa_hydraulics_unlock_in       
bool mfa_tms_in                     
bool mfa_joystick_enable_out        
bool mfa_steer_can_out              
bool mfa_steer_auto_out             
bool mfa_hydraulics_unlock_out      
bool mfa_tms_out                    