# Worklights System Command

std_msgs/Header header

bool enable             # Set true to enable the respective system
bool ignore_overrides   # Set true for respective system to ignore overrides
bool clear_override     # Set true to clear a system override flag

bool worklight_fh       # Set true to turn ON
bool worklight_rh       # Set true to turn ON
bool worklight_fl       # Set true to turn ON
bool worklight_rl       # Set true to turn ON
bool worklight_beacon   # Set true to turn ON