# Message file for srr_debug4

Header header

bool      Timer_Create_Error                      

bool      Thread_Create_Error                     

bool      ARM_Calibration_Error                   

bool      SPI_FEE_Error                           

bool      SPI_Comm_Error                          

bool      Socket_Write_Error                      

bool      DSP_Cal_Obsolete_62_Error               

bool      Socket_Read_error                       

bool      Socket_Init_Error                       

bool      Signal_Wait_Error                       

bool      Signal_Send_Error                       

bool      Signal_Create_Error                     

bool      Shared_Mem_Write_Error                  

bool      Shared_Mem_Read_Error                   

bool      Shared_Mem_Config_Error                 

bool      Share_Mem_Init_Error                    

bool      RAM_Test_Error                          

bool      Num_Errors                              

bool      MMAP_Memory_Error                       

bool      ISR_Attach_Error                        

bool      IPC_DRV_Write_Error                     

bool      IPC_DRV_Trigger_Error                   

bool      IPC_DRV_Sync_Error                      

bool      IPC_DRV_Read_Error                      

bool      IPC_DRV_Init_Error                      

bool      Interrupt_Enable_Error                  

bool      HIL_Format_Error                        

bool      Flash_Filesystem_Error                  

bool      Error_none                              

bool      DSP_Load_Read_Error                     

bool      DSP_Load_Open_Error                     

bool      DSP_Load_Address_Error                  

bool      DSP_ISP_Write_Error                     

bool      DSP_IPC_Read_Error                      

bool      DSP_IPC_Init                            

bool      DSP_Init_Error                          

bool      DSP_DRV_Start_Error                     

bool      DSP_DRV_Load_Error                      

bool      DSP_DRV_Init_Error                      

bool      DSP_DRV_Init2_error                     

bool      DSP_DRV_Init1_error                     

bool      DSP_Calibration_Error                   

bool      CAN_XMT_Error                           

bool      CAN_RCV_Error                           

bool      CAN_Hardware_Error                      

bool      Always_True                             

