# Message file for srr_feature_alert

Header header

uint8     LCMA_blis_ignored_track_id              

uint8     LCMA_blis_track_id                      

float32   LCMA_cvw_TTC                             # seconds

bool      CTA_TTC_Alert                           

float32   CTA_selected_track_ttc                   # seconds

uint16    CTA_selected_track                      

uint8     CTA_Alert                                # binary

bool      CTA_Active                               # binary

uint8     LCMA_cvw_cipv                           

uint8     LCMA_cvw_alert_state                    

uint8     LCMA_blis_alert_state                   

bool      LCMA_Active                             

