# Message file for srr_status1

Header header

bool      CAN_TX_LOOK_TYPE                        
bool          CAN_TX_LOOK_TYPE_Medium_Look=0
bool          CAN_TX_LOOK_TYPE_Long_Look=1

uint32    CAN_TX_DSP_TIMESTAMP                     # ms

float32   CAN_TX_YAW_RATE_CALC                     # deg/s

float32   CAN_TX_VEHICLE_SPEED_CALC                # m/s

uint16    CAN_TX_SCAN_INDEX                       

float32   CAN_TX_CURVATURE                         # 1/m

