# Message file for srr_status3

Header header

uint8     CAN_TX_ALIGNMENT_STATE                  
uint8         CAN_TX_ALIGNMENT_STATE_Off=0
uint8         CAN_TX_ALIGNMENT_STATE_Init=1
uint8         CAN_TX_ALIGNMENT_STATE_Automatic_Alignment=2
uint8         CAN_TX_ALIGNMENT_STATE_Factory_Alignment=3
uint8         CAN_TX_ALIGNMENT_STATE_Service_Alignment=4

uint8     CAN_TX_INTERFACE_VER_MINOR              

uint32    CAN_TX_SW_VERSION_ARM                   

uint8     CAN_TX_HW_VERSION                       

uint8     CAN_TX_INTERFACE_VERSION                

uint32    CAN_TX_SERIAL_NUM                       

