# Message file for srr_track

Header header

uint8     CAN_TX_DETECT_VALID_LEVEL               
uint8         CAN_TX_DETECT_VALID_LEVEL_Suspect_Detection=0
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_1=1
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_2=2
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_3=3
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_4=4
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_5=5
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_6=6
uint8         CAN_TX_DETECT_VALID_LEVEL_Level_7=7

bool      CAN_TX_DETECT_STATUS                    
bool          CAN_TX_DETECT_STATUS_No_Data=0
bool          CAN_TX_DETECT_STATUS_Valid_Data_Present=1

float32   CAN_TX_DETECT_RANGE_RATE                 # m/s

float32   CAN_TX_DETECT_RANGE                      # m

float32   CAN_TX_DETECT_ANGLE                      # deg

float32   CAN_TX_DETECT_AMPLITUDE                  # dBsm

