# Message file for AnalogIn

std_msgs/Header header

uint8     command                                 
uint8     analog_data_ch4_low_byte                
uint8     analog_data_ch4_high_bits               
uint8     analog_data_ch3_low_byte                
uint8     analog_data_ch3_high_bits               
uint8     analog_data_ch2_low_byte                
uint8     analog_data_ch2_high_bits               
uint8     analog_data_ch1_low_byte                
uint8     analog_data_ch1_high_bits               
