# Message file for AnsToCmdConnect

std_msgs/Header header

uint8     command                                 
uint8     cmd_connect_ans_d7                      
uint8     cmd_connect_ans_d6                      
uint8     cmd_connect_ans_d5                      
uint8     cmd_connect_ans_d4                      
uint8     cmd_connect_ans_d3                      
uint8     cmd_connect_ans_d2                      
uint8     cmd_connect_ans_d1                      
