# Message file for Command

std_msgs/Header header

uint8     command                                 
uint64    command_data                            
uint8     set_num                                 
uint8     paraset_byte6                     
uint8     paraset_byte5                     
uint8     paraset_byte4                     
uint8     paraset_byte3                     
uint8     paraset_byte2                     
uint8     paraset_byte1                     
uint8     set_active_9to16                        
uint8     set_active_1to8                         
