# Message file for Data4Sensors

Header header

uint8     data_sensor_1                           
uint8     warn_sensor_1
uint8     alarm_sensor_1

uint8     data_sensor_2 
uint8     warn_sensor_2
uint8     alarm_sensor_2                          

uint8     data_sensor_3 
uint8     warn_sensor_3
uint8     alarm_sensor_3                          

uint8     data_sensor_4 
uint8     warn_sensor_4
uint8     alarm_sensor_4                          
